name: 01-env-variable
on: 
  workflow_dispatch:
env: 
# env is different and environment is different
     ENVIRONMENT: "dev"
     APP_NAME: djtenalI
jobs:
   env-demo:
       runs-on: ubuntu-latest
       steps:
       - name: Print variables
         run: |
           echo "Printing Environmental Variable"
           echo "Application name is: $APP_NAME"
           echo "Environment is : $ENVIRONMENT"