name: 03-step-level-variable
on:
  workflow_dispatch:
jobs:
  dev-job:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "dev"
      APP_NAME: djtenali-dev-app
    steps:
    - name: Print variables
      run: |
       echo "Printing Environmental variables"
       echo "Application name is: $APP_NAME"
       echo "Environment is: $ENVIRONMENT"
    - name: print srep level variable
      env: 
        APP_VERSION: "1.0.0"
      run: |
       echo "Printing step level variables"
       echo "Application version is: $APP_VERSION"
       echo "Application name is: $APP_NAME"
       echo "Environment is: $ENVIRONMENT"


  prod-job:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "prod"
      APP_NAME: djtenali-prod-app
    steps:
    - name: Print variables
      run: |
        echo "Printing Environmental variables"
        echo "Application name is: $APP_NAME"
        echo "Environment is: $ENVIRONMENT"
    - name: print srep level variable
      env: 
        APP_VERSION: "1.0.0"
      run: |
        echo "Printing step level variables"
        echo "Application version is: $APP_VERSION"
        echo "Application name is: $APP_NAME"
        echo "Environment is: $ENVIRONMENT"          