name: Step-failure demo
on:
  workflow_dispatch:
jobs:
  my-first-job:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          sleep 10
          echo "step 1 is success"
      - name: Step 2
        run: |
          echo"intentionally failing this step"
          exit 1
      - name: Step 3
        run: 
          echo "this is sep 3"
      - name: Step 4
        run:
          echo " this is step 4 "
  my-second-job:
    name: second-job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 say hello again
        run: |
          sleep 5
          echo "************* hello again from second job"

        
        
      
